server:
  port: 40001
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: vmfhwprxm
    key-alias: spring

spring:
  data:
    mongodb:
      uri: mongodb://stage41:anjajdsid@stage41.xyz:27017
      database: member

logging:
  level:
    root: debug

auth-server:
  token_key:
    url: https://stage41.xyz:42222/oauth/token_key
